[project]
name = 'boostaid-smart-contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'
[contracts.funding-campaign]
path = 'contracts/funding-campaign.clar'
clarity_version = 2
epoch = 2.5

[contracts.fundraiser-nft]
path = 'contracts/fundraiser-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.promoter-nft]
path = 'contracts/promoter-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.promoter-rank]
path = 'contracts/promoter-rank.clar'
clarity_version = 2
epoch = 2.5

[contracts.treasury]
path = 'contracts/treasury.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
